### ISSUE TITLE
Binding that uses the /api/now/cmdbrelation/relation/ 

### ISSUE THREAD

**Issue by arthurzenika** [ServiceNow/PySNC#60]
In the following knowledge base documentation : https://support.servicenow.com/kb?id=kb_article_view&sysparm_article=KB0854577 a ReST API to extract information from relations with a depth level seems to indicate the possibility of getting related items in ServiceNow. This type of functionality would be super useful for the way we use PySNC. Any plans of looking into this and offering a binding to this functionality ? 

(probably related is #54)

**Comment by vetsin** [comment]
@arthurzenika it's not as much that it's not possible to mimic GlideElements to get type information and such, it's more-so that the ACL's involved and the additional db/request overhead isn't really worth it imo.

If I have a service account or such that needs CRUD to a single table, i don't want to open up ACLs or make two requests for one query. Not to mention this API is largely undocumented, so bad mojo to use it in an API like this.
